### ISSUE TITLE
高：予約確認→ICログインでおサイフケータイをリーダにかざすと例外が発生する

### ISSUE THREAD

**Issue by Kz-8** [diltd/Spacee_App#1]
例外は以下の通り。

```
07-21 06:43:51.037 6747-6761/jp.spacee.app.android.spacee_app W/BluetoothGatt: Unhandled exception in callback
                                                                               java.lang.ArrayIndexOutOfBoundsException: length=5; index=13
                                                                                   at jp.spacee.app.android.spacee_app.service.ICCReaderService$4.onAtrAvailable(ICCReaderService.java:434)
                                                                                   at com.acs.bluetooth.Acr1255uj1Reader.d(SourceFile:334)
                                                                                   at com.acs.bluetooth.Acr1255uj1Reader.a(SourceFile:272)
                                                                                   at com.acs.bluetooth.BluetoothReader.a(SourceFile:703)
                                                                                   at com.acs.bluetooth.BluetoothReaderGattCallback.onCharacteristicChanged(SourceFile:124)
                                                                                   at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:487)
                                                                                   at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:399)
                                                                                   at android.os.Binder.execTransact(Binder.java:458)
```

**Comment by Kz-8** [comment]
PR #16 で修正済み

**Comment by Kz-8** [comment]
7/31時点積み残し
