### ISSUE TITLE
高：予約時のID/PWログインでログインボタンを押すと異常終了する

### ISSUE THREAD

**Issue by Kz-8** [diltd/Spacee_App#10]
例外は以下の通り。

```
07-21 07:21:47.601 8709-8709/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: jp.spacee.app.android.spacee_app, PID: 8709
                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setImageBitmap(android.graphics.Bitmap)' on a null object reference
                                                     at jp.spacee.app.android.spacee_app.listener.FragmentBookListListener$3.getView(FragmentBookListListener.java:206)
                                                     at android.widget.AbsListView.obtainView(AbsListView.java:2474)
                                                     at android.widget.ListView.onMeasure(ListView.java:1173)
                                                     at android.view.View.measure(View.java:19147)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
                                                     at android.view.View.measure(View.java:19147)
                                                     at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1236)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:650)
                                                     at android.view.View.measure(View.java:19147)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
                                                     at android.view.View.measure(View.java:19147)
                                                     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:825)
                                                     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:511)
                                                     at android.view.View.measure(View.java:19147)
                                                     at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:934)
                                                     at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:973)
                                                     at android.view.View.measure(View.java:19147)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
                                                     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                     at android.view.View.measure(View.java:19147)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
                                                     at android.view.View.measure(View.java:19147)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
                                                     at android.view.View.measure(View.java:19147)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:991)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
                                                     at android.view.View.measure(View.java:19147)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
                                                     at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2690)
                                                     at android.view.View.measure(View.java:19147)
                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2481)
                                                     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1445)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1699)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1326)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6726)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:696)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
                                                     at android.os.Handler.handleCallback(Handler.java:815)
                                                     at android.os.Handler.dispatchMessage(Handler.java:104)
                                                     at android.os.Looper.loop(Looper.java:207)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5822)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
```

**Comment by Kz-8** [comment]
PR #16 で修正済み
