### ISSUE TITLE
中：アプリインストール直後の掲載者ログインで異常終了する

### ISSUE THREAD

**Issue by Kz-8** [diltd/Spacee_App#11]
一度アプリをアンインストールし、インストール直後にログイン。２回中２回発生。
再度アプリを起動した場合にはログイン出来る。

ID: api-tester@spacee.jp
PW: apitester

例外は以下の通り。

```
07-21 07:29:04.017 16412-16412/jp.spacee.app.android.spacee_app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: jp.spacee.app.android.spacee_app, PID: 16412
                                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean jp.spacee.app.android.spacee_app.comm.HttpCommGlueRoutines.providerUserSignin(java.lang.String, java.lang.String)' on a null object reference
                                                                                      at jp.spacee.app.android.spacee_app.listener.FragmentProviderLoginListener.onBtnLoginPWClicked(FragmentProviderLoginListener.java:34)
                                                                                      at jp.spacee.app.android.spacee_app.fragment.FragmentProviderLogin$5.onClick(FragmentProviderLogin.java:187)
                                                                                      at android.view.View.performClick(View.java:5265)
                                                                                      at android.view.View$PerformClick.run(View.java:21534)
                                                                                      at android.os.Handler.handleCallback(Handler.java:815)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                      at android.os.Looper.loop(Looper.java:207)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5822)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
```

**Comment by Kz-8** [comment]
修正を確認
