### ISSUE TITLE
高：予約時の利用者登録で登録時にエラーが発生している

### ISSUE THREAD

**Issue by Kz-8** [diltd/Spacee_App#12]
落ちるわけでは無いが以下のエラーが出力され、画面遷移されない。
これは請求先登録をした場合のケース。

```
07-21 07:46:27.366 30601-30601/jp.spacee.app.android.spacee_app W/System.err: org.json.JSONException: Value c94a8ea3d67eb2328ee06bdb23fae01c of type java.lang.String cannot be converted to JSONObject
07-21 07:46:27.366 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
07-21 07:46:27.366 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:160)
07-21 07:46:27.366 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
07-21 07:46:27.366 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at jp.spacee.app.android.spacee_app.listener.FragmentEntryPolicyListener.onBtnAgreeClicked(FragmentEntryPolicyListener.java:48)
07-21 07:46:27.366 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at jp.spacee.app.android.spacee_app.fragment.FragmentEntryPolicy$1.onClick(FragmentEntryPolicy.java:116)
07-21 07:46:27.366 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at android.view.View.performClick(View.java:5265)
07-21 07:46:27.366 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at android.view.View$PerformClick.run(View.java:21534)
07-21 07:46:27.367 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at android.os.Handler.handleCallback(Handler.java:815)
07-21 07:46:27.367 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
07-21 07:46:27.367 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at android.os.Looper.loop(Looper.java:207)
07-21 07:46:27.367 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5822)
07-21 07:46:27.367 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-21 07:46:27.367 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
07-21 07:46:27.367 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
```

これはカード登録したときのケース。

```
07-21 07:49:26.798 30601-30601/jp.spacee.app.android.spacee_app W/System.err: org.json.JSONException: Value 667d60b4b5c2d1cd432430ba9fb73087 of type java.lang.String cannot be converted to JSONObject
07-21 07:49:26.798 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
07-21 07:49:26.798 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:160)
07-21 07:49:26.798 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
07-21 07:49:26.798 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at jp.spacee.app.android.spacee_app.listener.FragmentEntryPolicyListener.onBtnAgreeClicked(FragmentEntryPolicyListener.java:48)
07-21 07:49:26.798 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at jp.spacee.app.android.spacee_app.fragment.FragmentEntryPolicy$1.onClick(FragmentEntryPolicy.java:116)
07-21 07:49:26.799 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at android.view.View.performClick(View.java:5265)
07-21 07:49:26.799 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at android.view.View$PerformClick.run(View.java:21534)
07-21 07:49:26.799 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at android.os.Handler.handleCallback(Handler.java:815)
07-21 07:49:26.799 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
07-21 07:49:26.799 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at android.os.Looper.loop(Looper.java:207)
07-21 07:49:26.799 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5822)
07-21 07:49:26.799 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-21 07:49:26.799 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
07-21 07:49:26.799 30601-30601/jp.spacee.app.android.spacee_app W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
```

**Comment by Kz-8** [comment]
ユーザ登録されているのを確認
