### ISSUE TITLE
高：カード連携のQRログインで認証時に異常終了する

### ISSUE THREAD

**Issue by Kz-8** [diltd/Spacee_App#13]
例外は以下の通り。

```
07-21 07:52:11.024 30601-30601/jp.spacee.app.android.spacee_app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: jp.spacee.app.android.spacee_app, PID: 30601
                                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                                      at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
                                                                                      at org.json.JSONTokener.nextValue(JSONTokener.java:94)
                                                                                      at org.json.JSONObject.<init>(JSONObject.java:156)
                                                                                      at org.json.JSONObject.<init>(JSONObject.java:173)
                                                                                      at jp.spacee.app.android.spacee_app.listener.FragmentLoginQRListener$3.onImageAvailable(FragmentLoginQRListener.java:205)
                                                                                      at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:648)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                      at android.os.Looper.loop(Looper.java:207)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5822)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
```

**Comment by Kz-8** [comment]
落ちるのは修正を確認
