### ISSUE TITLE
中：画面固定を行うとアプリケーションが異常終了する

### ISSUE THREAD

**Issue by Kz-8** [diltd/Spacee_App#2]
画面固定については以下を参照して下さい。
http://qiita.com/calciolife/items/db9edd5f873f81ce64aa

発生している例外は以下の通り。

```
07-21 06:45:43.747 6747-6747/jp.spacee.app.android.spacee_app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: jp.spacee.app.android.spacee_app, PID: 6747
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{jp.spacee.app.android.spacee_app/jp.spacee.app.android.spacee_app.activity.SpaceeAppMain}: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class fragment
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2596)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2678)
                                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                    at android.os.Looper.loop(Looper.java:207)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5822)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
                                                                                 Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class fragment
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                    at jp.spacee.app.android.spacee_app.activity.SpaceeAppMain.onCreate(SpaceeAppMain.java:180)
                                                                                    at android.app.Activity.performCreate(Activity.java:6308)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2543)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2678) 
                                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                    at android.os.Looper.loop(Looper.java:207) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5822) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749) 
                                                                                 Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class fragment
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                    at jp.spacee.app.android.spacee_app.activity.SpaceeAppMain.onCreate(SpaceeAppMain.java:180) 
                                                                                    at android.app.Activity.performCreate(Activity.java:6308) 
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2543) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2678) 
                                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                    at android.os.Looper.loop(Looper.java:207) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5822) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749) 
                                                                                 Caused by: java.lang.IllegalStateException: Fragment jp.spacee.app.android.spacee_app.fragment.FragmentTop did not create a view.
                                                                                    at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3471)
                                                                                    at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
                                                                                    at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:378)
                                                                                    at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:33)
                                                                                    at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:754)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                    at jp.spacee.app.android.spacee_app.activity.SpaceeAppMain.onCreate(SpaceeAppMain.java:180) 
                                                                                    at android.app.Activity.performCreate(Activity.java:6308) 
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2543) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2678) 
                                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                    at android.os.Looper.loop(Looper.java:207) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5822) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749) 
```

**Comment by Kz-8** [comment]
7/31時点積み残し
